### ISSUE TITLE
Environmental explosives (tar pots and barrels in Aqueduct and Rallypoint Delta) explode multiple times.

### ISSUE THREAD

**Issue by MeatMorning** [Sivelos1/SivsItemsRoR2#14]
1. When the player is within explosive barrels AoE range, they (barrels) blow up muliple times (causing oneshots on higher difficulties).
2. When the player is outside explosive barrels AoE range, they blow up as usual: only 1 time.
3. This behaviour disappears when this mod is disabled.

**Comment by MeatMorning** [comment]
Mod manager import code with all used modifications: obCHNovnYW

**Comment by SOMSTATE** [comment]
Also having this issue.

**Comment by Sivelos1** [comment]
Should be fixed.
