### ISSUE TITLE
Fire procs from Living Furnace don't deal any damage

### ISSUE THREAD

**Issue by MightyW0lf** [Sivelos1/SivsItemsRoR2#5]
Title. [A video showing the bug](https://youtu.be/_Ie44SOxnL8) (with proc chance configured to 100% for demonstration purposes, issue persists when on default configuration as well).

Mods:
* **Sivelos1-SivsItems-0.0.6**
* bbepis-BepInExPack-5.3.1
* tristanmcpherson-R2API-2.5.14
* Harb-DebugToolkit-3.4.2
* ThinkInvis-TILER2-3.0.4

**Comment by gaforb** [comment]
This is still broken as of the anniversary update - Burn debuff is applied but no damage is dealt

**Comment by Sivelos1** [comment]
Wow I kind of missed this for a while. Works as intended now though
